# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adsimdetector/releases/download/2023.11.2/ibek.ioc.schema.json

ioc_name: bl01t-ea-ioc-02
description: Example simulated camera for BL01T

entities:
  - type: ADSimDetector.simDetector
    PORT: det.cam
    P: BL01T-EA-TST-02
    R: ":CAM:"

  - type: ADCore.NDPvaPlugin
    PORT: det.pva
    PVNAME: BL01T-EA-TST-02:PVA:OUTPUT
    P: BL01T-EA-TST-02
    R: ":PVA:"
    NDARRAY_PORT: det.cam
